### ISSUE TITLE
Unable to locate download files

### ISSUE THREAD

**Issue by apavlinovic** [kwsch/ReMasters#1]
It may be a noobish question, but how do you locate the files that the game downloaded?

**Comment by kwsch** [comment]
People have posted the downloaded file data online if you are having trouble exporting the data from your device.

Closing this issue as this is unrelated to the usage of this program/lib.

**Comment by IscoV** [comment]
> 
> 
> People have posted the downloaded file data online if you are having trouble exporting the data from your device.
> 
> Closing this issue as this is unrelated to the usage of this program/lib.

Where?
