### ISSUE TITLE
SFX and Voice Clip ripping?

### ISSUE THREAD

**Issue by MisterPrawn** [kwsch/ReMasters#10]
It's probably been brought up before, but what's the status on being able to dump sfx and such from Masters? I'm really into the voices in this game, and I was hoping sound dumping and such would be possible soon-ish.

**Comment by kwsch** [comment]
sfx encryption is undocumented; can't implement any code without knowing how things work :)

It's currently outside the scope of ReMasters, so I'm closing this issue.

**Comment by VoltageMiner** [comment]
> 
> 
> It's probably been brought up before, but what's the status on being able to dump sfx and such from Masters? I'm really into the voices in this game, and I was hoping sound dumping and such would be possible soon-ish.

Soon took almost two years, but here we are. It has been done.

**Comment by MisterPrawn** [comment]
> 
> 
> > It's probably been brought up before, but what's the status on being able to dump sfx and such from Masters? I'm really into the voices in this game, and I was hoping sound dumping and such would be possible soon-ish.
> 
> Soon took almost two years, but here we are. It has been done.

Well, it's about time~
