### ISSUE TITLE
System Overflow exception during extract

### ISSUE THREAD

**Issue by SageSystems** [kwsch/ReMasters#23]
Apk version: 2.15.1 
Data downloaded on: 15/12/21
![image](https://user-images.githubusercontent.com/46354004/146421700-695f4623-3393-4d6d-8f04-a94d1997b0a1.png)
Memory in system: 14GB 
Edited console.cs:
```using System;
using ReMastersLib;

namespace ReMastersConsole
{
    public static class Program
    {
        private static void Main(string[] args)
        {
            if (args.Length > 1)
            {
                Console.WriteLine("Not a console app, really. Don't do that!");
                Console.ReadLine();
            }

            var paths = new GameDataPaths
            {
                UnpackedAPKPath = @"E:\mdat\apk",
                DownloadPath = @"E:\mdat\downloaded-resource-dir",
                ShardPath = @"E:\mdat\downloaded-resource-dir\assetdb_shard",

                OutputPath = @"E:\mdat\dump",
            };

            var settings = new DumpSettings(paths)
            {
                DumpStringsDL = true,
                DumpStringsAPK = true,

                DumpResources = true,
                DumpSound = true,
                DumpVideo = true,
                DumpProto = false,
            };

            settings.DumpGameData();
        }
    }
}
```

**Comment by SageSystems** [comment]
This extracts
![image](https://user-images.githubusercontent.com/46354004/146422203-b9dee416-8e8a-4a3e-9633-85d80fbf31b4.png)
this much of the Actors folder before having this error. I hope this is enough info to troubleshoot

**Comment by SageSystems** [comment]
#15 seems to reference this, @EternalStay did you ever fix the issue on your end?

**Comment by EternalStay** [comment]
In my current `Program.cs` file, I deleted the @ symbols and I put a `\` before the others `\`. I don't know if that's what solved my problem :/

So...
```C#
UnpackedAPKPath = "E:\\mdat\\apk",
DownloadPath = "E:\\mdat\\downloaded-resource-dir"
// [...]
```

**Comment by SageSystems** [comment]
thank you, will try this.

**Comment by SageSystems** [comment]
unfortunately the same error occurred at the same spot. seems that there must be a different fix. can you confirm your ability to extract the current download data? I can provide it privately if need be

**Comment by EternalStay** [comment]
I can extract the current download data, indeed.
Unfortunately, I can't remember how I fixed this problem, sorry :/ ...

**Comment by SageSystems** [comment]
could you send your code so I could test it out and check if it's a problem with my machine?

**Comment by SageSystems** [comment]
it's really awful this is a "works on my machine" type of issue where the issue is in the configuration of the building machine.

**Comment by VoltageMiner** [comment]
> it's really awful this is a "works on my machine" type of issue where the issue is in the configuration of the building machine.

Are you still having this issue?

**Comment by SageSystems** [comment]
I will need to recompile and test but I hope not, will get back to you in a few days

**Comment by SageSystems** [comment]
* hours to days

**Comment by VoltageMiner** [comment]
> * hours to days

Closing as .Net 6.0 isn't supported on VS2019 or earlier.
