### ISSUE TITLE
Running Program.cs on Linux

### ISSUE THREAD

**Issue by TrainerFromHoenn** [kwsch/ReMasters#24]
I've always worked on Windows but momentarily I'm stuck on using a Linux Machine. Since Visual Studio is Windows-based and for what I can see it's not possible to install it on Linux, is there another way to run this project? I'm using it to extract mainly the lsd dump and the 3d models to use them in Blender. Thanks in advance

**Comment by kwsch** [comment]
1. Install .NET Core 2.1 SDK (or later, and update the csproj)
2. Via command line, execute msbuild command to build the solution
3. Run the output executable?

There's also [Rider](https://www.jetbrains.com/rider/) which is a cross platform IDE.
