### ISSUE TITLE
LotteryUnitRates.pb removed?

### ISSUE THREAD

**Issue by homu-gamepress** [kwsch/ReMasters#9]
Getting "Couldn't find proto data file: LotteryUnitRate" error with the release data. Did they rename the file or delete it altogether?

**Comment by kwsch** [comment]
Wouldn't be surprising if they moved it server-side to prevent people from finding out drop rates.

**Comment by kwsch** [comment]
It's probably not worth investigating where this content has been relocated to.

Different possiblities:
* Saved as a temp file, local rate checks but not for new gacha rolls.
* Server sided api calls to prevent forgery/easy referencing

For now, the debug log indicating there isn't a proto to parse is probably enough; retaining the proto definition in src is preferred (for record's sake).
